doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                password: '%env(DATABASE_PASSWORD)%'
            gso:
                dbname: 'gso_in_202306'
                url: '%env(resolve:DATABASE_GSO_URL)%'
                password: '%env(DATABASE_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Main
            gso:
                connection: gso
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Gso:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Gso'
                        type: annotation
                        prefix: 'App\Entity\Gso'
                        alias: Gso
