doctrine:
    dbal:
        connections:
            default:
                driver: 'mysqli'
                user: 'wiagvokabula_adm'
                password: '%env(DATABASE_PASSWORD)%'
                host: '%env(DATABASE_HOST)%'
                port: 3306
                dbname: 'wiagvokabulare'
                server_version: '%env(DATABASE_SERVER_VERSION)%'
            gso:
                driver: 'mysqli'
                user: 'gsdatenbank_adm'
                password: '%env(DATABASE_GSO_PASSWORD)%'
                host: '%env(DATABASE_GSO_HOST)%'
                port: 3306
                dbname: 'gsdatenbank'
                server_version: '%env(DATABASE_GSO_SERVER_VERSION)%'

            #profiling_collect_backtrace: '%kernel.debug%' # unexpected error 'Invalid type for path "doctrine.dbal.connections.profiling_collect_backtrace". Expected "array", but got "bool' - documentation says it should be a bool
            use_savepoints: true

        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

    orm:
        enable_lazy_ghost_objects: true
        auto_generate_proxy_classes: true
        default_entity_manager: default
        controller_resolver:
            auto_mapping: false # "Symfony Mapped Route Parameters should be used as replacement." but these are only introduced in symfony 7.1 - still works...
        entity_managers:
            validate_xml_mapping: true

            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                report_fields_where_declared: true
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Main
            gso:
                connection: gso
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                report_fields_where_declared: true
                mappings:
                    Gso:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Gso'
                        type: attribute
                        prefix: 'App\Entity\Gso'
                        alias: Gso

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
