doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            gso:
                url: '%env(resolve:DATABASE_GSO_URL)%'
        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        enable_lazy_ghost_objects: true
        auto_generate_proxy_classes: true
        default_entity_manager: default
        #controller_resolver:
            #auto_mapping: false # "Symfony Mapped Route Parameters should be used as replacement." but these are only introduced in symfony 7.1
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Main
            gso:
                connection: gso
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Gso:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Gso'
                        type: attribute
                        prefix: 'App\Entity\Gso'
                        alias: Gso
